credentials:
  usernames:
    user1:
      name: MDS
      password: mds@qyng
      role: admin
    user2:
      name: IBP
      password: ibp@qyng
      role: user
    user3:
      name: YZ
      password: yuzhong@qyng
      role: user
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - user1@example.com
    - user2@example.com