[connections.postgres]
    type="sql"
    dialect="postgresql"
    username="postgres_readonly"
    password="qyng@2009"
    host="10.100.0.189" # IP or URL
    port=1235 # Port number
    database="postgres" # Database name
